### ISSUE TITLE
Error connecting from Power Bi to Atscale via "SQL Server Analysis Services"

### ISSUE THREAD

**Issue by alex4vk** [teccod/Logi-Atscale-Tableau-Issues#26]
Unable to set up Power Bi connection to Atscale via "SQL Server Analysis Services".

When connecting using Windows authorization, an error occurs:
<img src="https://user-images.githubusercontent.com/49229973/158597961-89396cc8-0a68-44c2-a746-01617da1dafa.jpg" width="600" />

![powerbi-atscale-1](https://user-images.githubusercontent.com/49229973/158599339-afcf10ba-5106-4336-88fe-a8718b802eb9.jpg)

Connecting via Excel using the "From Analysis Services" connector - works, but only through basic authorization. When you select "Use Windows Authentication" does not connect.

Atscale has domain authorization configured.
![powerbi-atscale-3](https://user-images.githubusercontent.com/49229973/158599851-a164b450-b62e-4c28-bc6e-8e971fcb6172.jpg)

In "Directory" -> "Test Configuration" domain users and their groups are available.
![powerbi-atscale-2](https://user-images.githubusercontent.com/49229973/158600811-cae1fc36-10e2-406d-87d9-d0dc5a7a4dd4.jpg)

Authorization under a domain user and password in Atscale - works.
Domain users have all the roles "Runtime Query User", "Organization Admin", "Design Center User" added.

What other settings might be required?

Atscale version 2021.3.0.3934
PowerBi Version 2.102.845.0

**Comment by alex4vk** [comment]
Addition to the description of the problem.

Only one user (admin) has been added to Atscale itself. 
At the same time, authorization of any domain users passes without errors.
![image8](https://user-images.githubusercontent.com/49229973/170003967-27dc253a-eae4-45e8-b05e-d986dd24dc34.jpg)

Connecting the "From Analysis Services" data source in Excel also runs without errors (with a domain account "user"):
![image6](https://user-images.githubusercontent.com/49229973/170004132-677337a8-9c61-4e3f-9985-09d16ff1dcbc.jpg)

![image5](https://user-images.githubusercontent.com/49229973/170004190-4d358ca9-7e2c-4919-95f3-4e52c77f1c36.jpg)

![image7](https://user-images.githubusercontent.com/49229973/170004207-89475ab7-9cee-4533-9655-d8072e634767.jpg)

When connected via PowerBi, "Analysis Services" data source, next behavior:
![image1](https://user-images.githubusercontent.com/49229973/170004380-0597414a-a50c-4fe0-842a-a2d88afd1c2a.jpg)

If you intentionally enter a non-existent account, an error occurs that the authorization failed.
The same error occurs if you enter an account in the "user" format (without a domain):
![image3](https://user-images.githubusercontent.com/49229973/170004487-036aadcd-e034-4a6c-a99b-24b552e494f9.jpg)

When entering an account in the format "teccod.ru\user", the error indicated in the first comment appears:
![image4](https://user-images.githubusercontent.com/49229973/170004553-9def8cb7-8705-4750-b2fd-c2c568fdc8ef.jpg)

**Comment by alex4vk** [comment]
The Atscale log shows the following entries before the "Microsoft.Analysisservices.AdomdClient.NamespacesMgr" error occurs.   

If you select the option "Use my current credentials":
<img src="https://user-images.githubusercontent.com/49229973/183390079-0e1feba2-5675-471c-89d7-bd632ac2eda8.png" width="400" />

Error in log:
(located in /opt/atscale/log/engine/debug.log)
```
2022-08-08 09:21:37,248 DEBUG [http-system-akka.actor.default-dispatcher-6] {} com.atscale.engine.http.EngineHttpAuthenticator - Would check HTTP credentials but none were provided
2022-08-08 09:21:37,258 DEBUG [atscale-akka.actor.ntlm-ldap-dispatcher-229422] {} com.atscale.engine.security.ActiveDirectoryActor - NTLM Type1 Connect & Bind completed after 2,11 ms
2022-08-08 09:21:37,266 DEBUG [atscale-akka.actor.ntlm-ldap-dispatcher-229423] {} com.atscale.engine.security.ActiveDirectoryActor - NTLM Type3 Bind failed after 1,51 ms
2022-08-08 09:21:37,266 WARN  [atscale-akka.actor.ntlm-ldap-dispatcher-229423] {} com.atscale.engine.security.ActiveDirectoryActor - Error while trying to authorize NTLM against LDAP: 8009030C: LdapErr: DSID-0C090585, comment: AcceptSecurityContext error, data 52e, v4f7c
com.unboundid.ldap.sdk.LDAPBindException: 8009030C: LdapErr: DSID-0C090585, comment: AcceptSecurityContext error, data 52e, v4f7c
        at com.unboundid.ldap.sdk.LDAPConnection.bind(LDAPConnection.java:2401)
        at com.atscale.engine.security.ActiveDirectoryActor.$anonfun$authorizeNtlmLdapChallengeResponse$2(ActiveDirectoryManager.scala:441)
        at org.gerweck.scala.util.timed$.apply(timed.scala:18)
        at com.atscale.engine.security.ActiveDirectoryActor.$anonfun$authorizeNtlmLdapChallengeResponse$1(ActiveDirectoryManager.scala:441)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-08-08 09:21:37,273 DEBUG [http-system-akka.actor.default-dispatcher-13] {} com.atscale.engine.http.EngineHttpAuthenticator - Would check HTTP credentials but none were provided
```

If you select the "Use alternate credentials" option and enter an account with a domain name:
<img src="https://user-images.githubusercontent.com/49229973/183390825-c0a555ba-ea65-418f-98af-33850cdb2048.png" width="400" />

Error in log:
(located in /opt/atscale/log/engine/debug.log)
```
2022-08-08 09:23:23,318 DEBUG [http-system-akka.actor.default-dispatcher-7] {} com.atscale.engine.http.EngineHttpAuthenticator - Would check HTTP credentials but none were provided
```

If you enter an account without a domain (e.g. "user"), there are no connection entries in the log.

**Comment by carmenlogue73** [comment]
I talked to AtScale support today about this today -- and since you found that Excel does not work with Windows Authentication, this points to something not get passed through or some misconfiguration of LDAP configuration or settings.  Can you confirm that Windows Authorization is enabled on the AD server?  We are working on this with a customer so will update here as we learn more.

**Comment by psteiwer** [comment]
Did you configure AtScale to use Windows Authentication?

Enabling Windows authentication

    Log in to AtScale.
    Go to Settings > Engine.
    Locate the auth.ntlm.enabled setting and enable it.

**Comment by alex4vk** [comment]
Thanks for the comments!

@carmenlogue73 Windows authorization on the AD server must be enabled. How can we check its work? We are using Windows Server 2022 Standard. Authorization via LDAP in Atscale works. Authorization from another workstation in the domain passes without errors. Below is an example of NTLM settings in group policies:
<img src="https://user-images.githubusercontent.com/49229973/188809809-39d9f3c1-2957-4bae-a287-e10ba5a0ce91.png" width="600" />

@psteiwer Yes, it's not mentioned in the description above, but the setting "auth.ntlm.enabled" was enabled. Atscale Engine has been restarted after being powered on. But the connection error still remains.
<img src="https://user-images.githubusercontent.com/49229973/188810161-83b30337-2938-4691-8a5d-fd6e87eb04c2.png" width="600" />
